// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cliente.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	cliente.proto

It has these top-level messages:
	RequisicaoCliente
	RetornoCliente
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RequisicaoCliente struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nome string `protobuf:"bytes,2,opt,name=nome" json:"nome,omitempty"`
}

func (m *RequisicaoCliente) Reset()                    { *m = RequisicaoCliente{} }
func (m *RequisicaoCliente) String() string            { return proto1.CompactTextString(m) }
func (*RequisicaoCliente) ProtoMessage()               {}
func (*RequisicaoCliente) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequisicaoCliente) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequisicaoCliente) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

type RetornoCliente struct {
	IdResultado   int64  `protobuf:"varint,1,opt,name=idResultado" json:"idResultado,omitempty"`
	NomeResultado string `protobuf:"bytes,2,opt,name=nomeResultado" json:"nomeResultado,omitempty"`
}

func (m *RetornoCliente) Reset()                    { *m = RetornoCliente{} }
func (m *RetornoCliente) String() string            { return proto1.CompactTextString(m) }
func (*RetornoCliente) ProtoMessage()               {}
func (*RetornoCliente) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RetornoCliente) GetIdResultado() int64 {
	if m != nil {
		return m.IdResultado
	}
	return 0
}

func (m *RetornoCliente) GetNomeResultado() string {
	if m != nil {
		return m.NomeResultado
	}
	return ""
}

func init() {
	proto1.RegisterType((*RequisicaoCliente)(nil), "proto.RequisicaoCliente")
	proto1.RegisterType((*RetornoCliente)(nil), "proto.RetornoCliente")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AddServiceCliente service

type AddServiceClienteClient interface {
	VerCliente(ctx context.Context, in *RequisicaoCliente, opts ...grpc.CallOption) (*RetornoCliente, error)
}

type addServiceClienteClient struct {
	cc *grpc.ClientConn
}

func NewAddServiceClienteClient(cc *grpc.ClientConn) AddServiceClienteClient {
	return &addServiceClienteClient{cc}
}

func (c *addServiceClienteClient) VerCliente(ctx context.Context, in *RequisicaoCliente, opts ...grpc.CallOption) (*RetornoCliente, error) {
	out := new(RetornoCliente)
	err := grpc.Invoke(ctx, "/proto.AddServiceCliente/verCliente", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AddServiceCliente service

type AddServiceClienteServer interface {
	VerCliente(context.Context, *RequisicaoCliente) (*RetornoCliente, error)
}

func RegisterAddServiceClienteServer(s *grpc.Server, srv AddServiceClienteServer) {
	s.RegisterService(&_AddServiceCliente_serviceDesc, srv)
}

func _AddServiceCliente_VerCliente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequisicaoCliente)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceClienteServer).VerCliente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddServiceCliente/VerCliente",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceClienteServer).VerCliente(ctx, req.(*RequisicaoCliente))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddServiceCliente_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddServiceCliente",
	HandlerType: (*AddServiceClienteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "verCliente",
			Handler:    _AddServiceCliente_VerCliente_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cliente.proto",
}

func init() { proto1.RegisterFile("cliente.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xe6, 0x5c,
	0x82, 0x41, 0xa9, 0x85, 0xa5, 0x99, 0xc5, 0x99, 0xc9, 0x89, 0xf9, 0xce, 0x10, 0x15, 0x42, 0x7c,
	0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42,
	0x5c, 0x2c, 0x79, 0xf9, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x52,
	0x04, 0x17, 0x5f, 0x50, 0x6a, 0x49, 0x7e, 0x51, 0x1e, 0x5c, 0x97, 0x02, 0x17, 0x77, 0x66, 0x4a,
	0x50, 0x6a, 0x71, 0x69, 0x4e, 0x49, 0x62, 0x4a, 0x3e, 0x54, 0x3b, 0xb2, 0x90, 0x90, 0x0a, 0x17,
	0x2f, 0x48, 0x2f, 0x42, 0x0d, 0xc4, 0x40, 0x54, 0x41, 0xa3, 0x20, 0x2e, 0x41, 0xc7, 0x94, 0x94,
	0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x98, 0xe1, 0xb6, 0x5c, 0x5c, 0x65, 0xa9, 0x45, 0x30,
	0x9e, 0x04, 0xc4, 0x13, 0x7a, 0x18, 0x4e, 0x97, 0x12, 0x85, 0xcb, 0x20, 0xbb, 0x2d, 0x89, 0x0d,
	0x2c, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x3f, 0x5a, 0x7c, 0x05, 0x01, 0x00, 0x00,
}
